name: Main Branch Protection

on:
  pull_request:
    branches:
      - Release

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != develop ]]; 
          then
            echo "Error: Pull request must come from 'develop'"
            exit 1
          fi
